version: 1.0.{build}
build_script:
- nuget restore
  release:HQF.XSLT.NetHelper-v$(appveyor_build_version)
  description: Beta
  provider: GitHub
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
